os:
    - linux
env:
    - VIVTESTFILES=/tmp/vivtestfiles
language: python
python:
    - "2.7_with_system_site_packages"
install:
    - git clone https://github.com/vivisect/vivtestfiles.git /tmp/vivtestfiles
    - "travis_retry sudo apt-get -qq install libfreetype6-dev liblcms2-dev python-qt4 ghostscript libffi-dev libjpeg-turbo-progs cmake imagemagick"
    - pip install msgpack-python
script: py.test
